django_test/website/music/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	#/music/
    url(r'^$',views.index,name='index'),

    #/music/id/
    url(r'^(?P<album_id>[0-9]+)/$',views.detail,name='detail'),
]

django_test/website/website/urls.py
from django.conf.urls import include,url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls')),
]

django_test/website/music/models.py
# # -*- coding: utf-8 -*-
# from __future__ import unicode_literals

# from django.db import models

# # Create your models here.
from django.db import models

class Album(models.Model):
	artist=models.CharField(max_length=250)
	album_title=models.CharField(max_length=500)
	gener=models.CharField(max_length=100)
	album_logo=models.CharField(max_length=1000)
	#String Representation of object
	def __str__(self):
		return self.album_title+"-"+self.artist

class Song(models.Model):
	album=models.ForeignKey(Album,on_delete=models.CASCADE)
	file_type=models.CharField(max_length=10)
	song_title=models.CharField(max_length=250)

	def __str__(self):
		return self.song_title

django_test/website/music/views.py
from django.http import Http404
#from django.http import HttpResponse
from django.shortcuts import render 
#from django.template import loader
from .models import Album

def index(request):
	all_albums=Album.objects.all()
	
	#template=loader.get_template('music/index.html')
	context={
		'all_albums':all_albums,
	}
	return render(request,'music/index.html',context)
	#return HttpResponse(template.render(context,request))

def detail(request,album_id):
	try:
		album=Album.objects.get(pk=album_id)
	except Album.DoesNotExist:
		raise Http404("Album Does Not exist")
	return render(request,'music/detail.html',{"album":album})
	#return HttpResponse("<h2>Details for Album id:"+str(album_id)+"</h2>")

django_test/website/music/templates/music/detail.html
<!-- <img src="{{ album.album_logo }}"> -->

<h1>{{ album.album_title }}</h1>
<h3>{{ album.artist}}</h3>
<ul>
	{% for song in album.song_set.all %}
		<li>{{song.song_title}}-{{song.song_type}}</li>
	{% endfor %}
</ul>

django_test/website/music/templates/music/index.html
{% if all_albums %}

<h1>List of all albums</h1>
<ul>
	{% for album in all_albums %}
		<!-- Hardcord URL-->
		<!-- <li><a href="/music/{{album.id}}/">{{album.album_title}}</a></li> -->

		<!--Dynamic URL-->
		<li><a href="{% 'detail' album.id %}">{{ album.album_title }}</a></li>
	{% endfor %}
</ul>
{% else %}
	<h3>You Don't Have any Albums</h3>

{% endif %}